### ISSUE TITLE
Doesn't work with ExtractTextPlugin?

### ISSUE THREAD

**Issue by zerbons** [purifycss/purifycss-webpack-plugin#38]
I use `ExtractTextPlugin` for production and receive these errors:

```
ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'purifycss' in /app/src
 @ ./src/index.js 23:0-23

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'purifycss' in /app/src
 @ ./src/index.js 22:0-46
```

```
// /app/src/index.js
require('./styles.css');
require('./styles2.css');
```

Loaders look like this (passed into relevant loader):
```
ExtractTextPlugin.extract('style-loader', 'css!purifycss');
ExtractTextPlugin.extract('style-loader', 'css!purifycss!less');
ExtractTextPlugin.extract('style-loader', 'css!purifycss!sass');
```

**Comment by iam4x** [comment]
I'm getting the same error

**Comment by iam4x** [comment]
It happens without `ExtracTextPlugin` too, I'm might be missing something.

**Comment by iam4x** [comment]
I've figured out the problem, dropped a PR. Before it gets merged you can use:

`$ npm install --save-dev purifycss-loader@git@github.com:iam4x/purifycss-webpack-plugin.git#patch-1`

**Comment by gangyal** [comment]
any updates here guys? if you fix the loader file, it's still bad. does not work with extract text.

**Comment by IngwiePhoenix** [comment]
Is there an update to this?

**Comment by carlosepp** [comment]
I can confirm that @iam4x patch works, let us know when you release the PR to the master branch so we update :)

**Comment by IngwiePhoenix** [comment]
@carlosepp Good to know. I wrote my own plugin for the meantime that works, so I am good to go. :) But it'd be nice to use a more official one.

**Comment by carlosepp** [comment]
@IngwiePhoenix , I am curious if you open sourced the plugin?, would like to see what you came up with, actually it worked well testing in local environment but it throws me an error in production:

```npm ERR! Cloning into bare repository '/app/.npm/_git-remotes/ssh-git-github-com-iam4x-purifycss-webpack-plugin-git-5d13d3b1'…``` @iam4x , I would really appreciate you let us know when you merge the patch into master :pray: thanks for your work

**Comment by IngwiePhoenix** [comment]
@carlosepp 
https://github.com/DragonsInn/BIRD3/tree/master/util
Check `purify-plugin.js` and its usage within `webpack.config.js`. I am thinking of using this plus PostCSS to create a plugin that specializes purely on pressing down CSS files written out by stuff like `extract-text-plugin`'n such. :) For now, it lives within the project, but feel free to copy and re-use!

**Comment by carlosepp** [comment]
@IngwiePhoenix  thanks a lot !, quite useful implementation, you da man :)

**Comment by IngwiePhoenix** [comment]
@carlosepp Thanks :)

**Comment by carlosepp** [comment]
@zerbons are you planning to merge [this patch](https://github.com/iam4x/purifycss-webpack-plugin#patch-1) from @iam4x and create a release anytime soon?

**Comment by zerbons** [comment]
@carlosepp i do not have access... that is a question for @kennyt
