### ISSUE TITLE
Example with `.js/.jsx` files?

### ISSUE THREAD

**Issue by iam4x** [purifycss/purifycss-webpack-plugin#40]
I'm trying to use PurifyCSS but without luck, I don't have an `index.html` entry file since it's an SPA bundled by webpack.

`new PurifyCssPlugin(path.join(__dirname, '../app'), '/index.js')` ?

My CSS build has the same size, ideas?

**Comment by zerbons** [comment]
@iam4x were you able to get it working at all?

**Comment by IngwiePhoenix** [comment]
Is this still an issue? It seems to be working for me.

**Comment by iam4x** [comment]
Yep :+1:
